### PR TITLE
added Travis CI

### PR DESCRIPTION
**Pull request by averias**

### CODE REVIEW

**Comment by gkorland** [comment]
Great! one thing I think you should consider is having a nightly run this way whenever a break change is added to RedisGraph (which shouldn't be too common) you'll get a notification.

**Comment by averias** [comment]
Yes, I did as I commented on the issue you opened. I created a daily cronjob running the test against your `edge` RedisTimeSeries image

**Comment by gkorland** [comment]
ohhh... thanks!

**Comment by averias** [comment]
Thanks to you for taking care of the CI with Actions!

**Pull request merged**
